using System.Runtime.InteropServices.JavaScript;

namespace WasmWebGL;

/// <summary>
/// Generated by WebGL.tt at 2023-10-08 11:10:22 UTC
/// Bindings are generated based on specification from webgl.spec.xml
/// </summary>
public static partial class WebGL
{
	[JSImport("InitCanvasWebGL", "webgl-bindings.js")]
	public static partial void InitCanvasWebGL(int width, int height);

	[JSImport("glViewport", "webgl-bindings.js")]
	public static partial void glViewport(int x, int y, int width, int height);

	[JSImport("glClearColor", "webgl-bindings.js")]
	public static partial void glClearColor(float r, float g, float b, float a);

	[JSImport("glClear", "webgl-bindings.js")]
	public static partial void glClear(int flags);

	[JSImport("glEnable", "webgl-bindings.js")]
	public static partial void glEnable(int mode);

	[JSImport("glGenVertexArrays", "webgl-bindings.js")]
	public static partial int glGenVertexArrays();

	[JSImport("glBindVertexArray", "webgl-bindings.js")]
	public static partial void glBindVertexArray(int array);

	[JSImport("glVertexAttribPointer", "webgl-bindings.js")]
	public static partial void glVertexAttribPointer(int index, int size, int type, int normalized, int stride, int offset);

	[JSImport("glEnableVertexAttribArray", "webgl-bindings.js")]
	public static partial void glEnableVertexAttribArray(int index);

	[JSImport("glGenBuffers", "webgl-bindings.js")]
	public static partial int glGenBuffers();

	[JSImport("glBindBuffer", "webgl-bindings.js")]
	public static partial void glBindBuffer(int target, int buffer);

	[JSImport("glBufferData", "webgl-bindings.js")]
	public static partial void glBufferData(int target, int size, string jsonData, int usage, int type);

	[JSImport("glCreateShader", "webgl-bindings.js")]
	public static partial int glCreateShader(int type);

	[JSImport("glShaderSource", "webgl-bindings.js")]
	public static partial void glShaderSource(int shader, string source);

	[JSImport("glCompileShader", "webgl-bindings.js")]
	public static partial void glCompileShader(int shader);

	[JSImport("glGetShaderParameter", "webgl-bindings.js")]
	public static partial bool glGetShaderParameter(int shader, int pname);

	[JSImport("glGetShaderInfoLog", "webgl-bindings.js")]
	public static partial string glGetShaderInfoLog(int shader);

	[JSImport("glCreateProgram", "webgl-bindings.js")]
	public static partial int glCreateProgram();

	[JSImport("glAttachShader", "webgl-bindings.js")]
	public static partial void glAttachShader(int program, int shader);

	[JSImport("glLinkProgram", "webgl-bindings.js")]
	public static partial void glLinkProgram(int program);

	[JSImport("glGetUniformLocation", "webgl-bindings.js")]
	public static partial int glGetUniformLocation(int program, string uniformName);

	[JSImport("glUniformMatrix4fv", "webgl-bindings.js")]
	public static partial void glUniformMatrix4fv(int uniformLocation, string jsonData, bool transpose);

	[JSImport("glDrawArrays", "webgl-bindings.js")]
	public static partial void glDrawArrays(int mode, int first, int count);

	[JSImport("glDrawElements", "webgl-bindings.js")]
	public static partial void glDrawElements(int mode, int count, int type, int offset);

	[JSImport("glUseProgram", "webgl-bindings.js")]
	public static partial void glUseProgram(int program);

	public const int GL_COLOR_BUFFER_BIT = 0x4000;
	public const int GL_POINTS = 0x0000;
	public const int GL_LINES = 0x0001;
	public const int GL_LINE_LOOP = 0x0002;
	public const int GL_LINE_STRIP = 0x0003;
	public const int GL_TRIANGLES = 0x0004;
	public const int GL_TRIANGLE_STRIP = 0x0005;
	public const int GL_TRIANGLE_FAN = 0x0006;
	public const int GL_MODELVIEW = 0x1700;
	public const int GL_PROJECTION = 0x1701;
	public const int GL_VERSION = 0x1F02;
	public const int GL_TRUE = 1;
	public const int GL_FALSE = 0;
	public const int GL_FRAGMENT_SHADER = 0x8B30;
	public const int GL_VERTEX_SHADER = 0x8B31;
	public const int GL_COMPILE_STATUS = 0x8B81;
	public const int GL_LINK_STATUS = 0x8B82;
	public const int GL_ARRAY_BUFFER = 0x8892;
	public const int GL_STATIC_DRAW = 0x88E4;
	public const int GL_DYNAMIC_DRAW = 0x88E8;
	public const int GL_FLOAT = 0x1406;
	public const int GL_UNSIGNED_INT = 0x1405;
	public const int GL_INT = 0x1404;
	public const int GL_DEBUG_OUTPUT = 0x92E0;
	public const int GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x8242;
	public const int GL_ELEMENT_ARRAY_BUFFER = 0x8893;
	public const int GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895;
	public const int GL_LINE = 0x1B01;
	public const int GL_FILL = 0x1B02;
	public const int GL_FRONT_AND_BACK = 0x0408;
	public const int GL_DEBUG_SEVERITY_HIGH = 0x9146;
	public const int GL_DEBUG_SEVERITY_LOW = 0x9148;
	public const int GL_DEBUG_SEVERITY_MEDIUM = 0x9147;
	public const int GL_DEBUG_SEVERITY_NOTIFICATION = 0x826B;
	public const int GL_TEXTURE_2D = 0x0DE1;
	public const int GL_RGB = 0x1907;
	public const int GL_RGBA = 0x1908;
	public const int GL_UNSIGNED_BYTE = 0x1401;
	public const int GL_TEXTURE_WRAP_S = 0x2802;
	public const int GL_TEXTURE_WRAP_T = 0x2803;
	public const int GL_TEXTURE_MIN_FILTER = 0x2801;
	public const int GL_TEXTURE_MAG_FILTER = 0x2800;
	public const int GL_REPEAT = 0x2901;
	public const int GL_LINEAR = 0x2601;
	public const int GL_LINEAR_MIPMAP_LINEAR = 0x2703;
	public const int GL_NEAREST = 0x2600;
	public const int GL_NEAREST_MIPMAP_LINEAR = 0x2702;
	public const int GL_NEAREST_MIPMAP_NEAREST = 0x2700;
	public const int GL_TEXTURE0 = 0x84C0;
	public const int GL_TEXTURE1 = 0x84C1;
	public const int GL_TEXTURE2 = 0x84C2;
	public const int GL_TEXTURE3 = 0x84C3;
	public const int GL_TEXTURE4 = 0x84C4;
	public const int GL_TEXTURE5 = 0x84C5;
	public const int GL_TEXTURE6 = 0x84C6;
	public const int GL_TEXTURE7 = 0x84C7;
	public const int GL_TEXTURE8 = 0x84C8;
	public const int GL_TEXTURE9 = 0x84C9;
	public const int GL_TEXTURE10 = 0x84CA;
	public const int GL_TEXTURE11 = 0x84CB;
	public const int GL_TEXTURE12 = 0x84CC;
	public const int GL_TEXTURE13 = 0x84CD;
	public const int GL_TEXTURE14 = 0x84CE;
	public const int GL_TEXTURE15 = 0x84CF;
	public const int GL_TEXTURE16 = 0x84D0;
	public const int GL_TEXTURE17 = 0x84D1;
	public const int GL_TEXTURE18 = 0x84D2;
	public const int GL_TEXTURE19 = 0x84D3;
	public const int GL_TEXTURE20 = 0x84D4;
	public const int GL_TEXTURE21 = 0x84D5;
	public const int GL_TEXTURE22 = 0x84D6;
	public const int GL_TEXTURE23 = 0x84D7;
	public const int GL_TEXTURE24 = 0x84D8;
	public const int GL_TEXTURE25 = 0x84D9;
	public const int GL_TEXTURE26 = 0x84DA;
	public const int GL_TEXTURE27 = 0x84DB;
	public const int GL_TEXTURE28 = 0x84DC;
	public const int GL_TEXTURE29 = 0x84DD;
	public const int GL_TEXTURE30 = 0x84DE;
	public const int GL_TEXTURE31 = 0x84DF;
	public const int GL_FRAMEBUFFER = 0x8D40;
	public const int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
	public const int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
	public const int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
	public const int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
	public const int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
	public const int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
	public const int GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 0x8DA7;
	public const int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8CD1;
	public const int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8CD0;
	public const int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
	public const int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
	public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8CD3;
	public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8CD4;
	public const int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8CD2;
	public const int GL_FRAMEBUFFER_BINDING = 0x8CA6;
	public const int GL_FRAMEBUFFER_COMPLETE = 0x8CD5;
	public const int GL_FRAMEBUFFER_DEFAULT = 0x8218;
	public const int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8CD6;
	public const int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8CDB;
	public const int GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8;
	public const int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8CD7;
	public const int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8D56;
	public const int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8CDC;
	public const int GL_FRAMEBUFFER_SRGB = 0x8DB9;
	public const int GL_FRAMEBUFFER_UNDEFINED = 0x8219;
	public const int GL_FRAMEBUFFER_UNSUPPORTED = 0x8CDD;
	public const int GL_COLOR_ATTACHMENT0 = 0x8CE0;
	public const int GL_COLOR_ATTACHMENT1 = 0x8CE1;
	public const int GL_COLOR_ATTACHMENT10 = 0x8CEA;
	public const int GL_COLOR_ATTACHMENT11 = 0x8CEB;
	public const int GL_COLOR_ATTACHMENT12 = 0x8CEC;
	public const int GL_COLOR_ATTACHMENT13 = 0x8CED;
	public const int GL_COLOR_ATTACHMENT14 = 0x8CEE;
	public const int GL_COLOR_ATTACHMENT15 = 0x8CEF;
	public const int GL_COLOR_ATTACHMENT16 = 0x8CF0;
	public const int GL_COLOR_ATTACHMENT17 = 0x8CF1;
	public const int GL_COLOR_ATTACHMENT18 = 0x8CF2;
	public const int GL_COLOR_ATTACHMENT19 = 0x8CF3;
	public const int GL_COLOR_ATTACHMENT2 = 0x8CE2;
	public const int GL_COLOR_ATTACHMENT20 = 0x8CF4;
	public const int GL_COLOR_ATTACHMENT21 = 0x8CF5;
	public const int GL_COLOR_ATTACHMENT22 = 0x8CF6;
	public const int GL_COLOR_ATTACHMENT23 = 0x8CF7;
	public const int GL_COLOR_ATTACHMENT24 = 0x8CF8;
	public const int GL_COLOR_ATTACHMENT25 = 0x8CF9;
	public const int GL_COLOR_ATTACHMENT26 = 0x8CFA;
	public const int GL_COLOR_ATTACHMENT27 = 0x8CFB;
	public const int GL_COLOR_ATTACHMENT28 = 0x8CFC;
	public const int GL_COLOR_ATTACHMENT29 = 0x8CFD;
	public const int GL_COLOR_ATTACHMENT3 = 0x8CE3;
	public const int GL_COLOR_ATTACHMENT30 = 0x8CFE;
	public const int GL_COLOR_ATTACHMENT31 = 0x8CFF;
	public const int GL_COLOR_ATTACHMENT4 = 0x8CE4;
	public const int GL_COLOR_ATTACHMENT5 = 0x8CE5;
	public const int GL_COLOR_ATTACHMENT6 = 0x8CE6;
	public const int GL_COLOR_ATTACHMENT7 = 0x8CE7;
	public const int GL_COLOR_ATTACHMENT8 = 0x8CE8;
	public const int GL_COLOR_ATTACHMENT9 = 0x8CE9;
	public const int GL_RENDERBUFFER = 0x8D41;
	public const int GL_RENDERBUFFER_ALPHA_SIZE = 0x8D53;
	public const int GL_RENDERBUFFER_BINDING = 0x8CA7;
	public const int GL_RENDERBUFFER_BLUE_SIZE = 0x8D52;
	public const int GL_RENDERBUFFER_DEPTH_SIZE = 0x8D54;
	public const int GL_RENDERBUFFER_GREEN_SIZE = 0x8D51;
	public const int GL_RENDERBUFFER_HEIGHT = 0x8D43;
	public const int GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8D44;
	public const int GL_RENDERBUFFER_RED_SIZE = 0x8D50;
	public const int GL_RENDERBUFFER_SAMPLES = 0x8CAB;
	public const int GL_RENDERBUFFER_STENCIL_SIZE = 0x8D55;
	public const int GL_RENDERBUFFER_WIDTH = 0x8D42;
	public const int GL_DEPTH = 0x1801;
	public const int GL_DEPTH24_STENCIL8 = 0x88F0;
	public const int GL_DEPTH32F_STENCIL8 = 0x8CAD;
	public const int GL_DEPTH_ATTACHMENT = 0x8D00;
	public const int GL_DEPTH_BIAS = 0x0D1F;
	public const int GL_DEPTH_BITS = 0x0D56;
	public const int GL_DEPTH_BUFFER_BIT = 0x00000100;
	public const int GL_DEPTH_CLAMP = 0x864F;
	public const int GL_DEPTH_CLEAR_VALUE = 0x0B73;
	public const int GL_DEPTH_COMPONENT = 0x1902;
	public const int GL_DEPTH_COMPONENT16 = 0x81A5;
	public const int GL_DEPTH_COMPONENT24 = 0x81A6;
	public const int GL_DEPTH_COMPONENT32 = 0x81A7;
	public const int GL_DEPTH_COMPONENT32F = 0x8CAC;
	public const int GL_DEPTH_FUNC = 0x0B74;
	public const int GL_DEPTH_RANGE = 0x0B70;
	public const int GL_DEPTH_SCALE = 0x0D1E;
	public const int GL_DEPTH_STENCIL = 0x84F9;
	public const int GL_DEPTH_STENCIL_ATTACHMENT = 0x821A;
	public const int GL_DEPTH_TEST = 0x0B71;
	public const int GL_DEPTH_TEXTURE_MODE = 0x884B;
	public const int GL_DEPTH_WRITEMASK = 0x0B72;
}
